name: Sample workflow bra1
on:
  push:
jobs:
  bra1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -a
          echo "" 
          git branch -a
      - uses: sokuhatiku/ftp-download-artifact@v1
        with:
          name: lisp-trpg
          host: lisp-trpg.sakura.ne.jp
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          secure: false
          remote-path: /home/lisp-trpg/www/HTML
